index:
    path: /
    controller: App\Controller\TweetController::index

ver_tweet:
    path: /tweet/{id}
    controller: App\Controller\TweetController::getTweet
    methods: ["GET"]

ver_usuario:
   path: /users/{id}
  controller: App\Controller\TweetController::getTweetfonyUser
  methods: ["GET"]

post_usuario:
  path: /users
  controller: App\Controller\TweetController::postTweetfonyUser
  methods: ["POST"]

post_tweets:
  path: /tweet
  controller: App\Controller\TweetController::postTweet
  methods: ["POST"]

put_user:
  path: /users/{id}
  controller: App\Controller\TweetController::putTweetfonyUser
  methods: ["PUT"]

put_tweet:
  path: /tweet/{id}
  controller: App\Controller\TweetController::putTweet
  methods: ["PUT"]

delete_user:
  path: /users/{id}
  controller: App\Controller\TweetController::deleteTweetfonyUser
  methods: ["DELETE"]

delete_tweet:
  path: /tweet/{id}
  controller: App\Controller\TweetController::deleteTweet
  methods: ["DELETE"]
